#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --

# Get result of last build
JSON=$(wget -qO- http://localhost:8080/job/$JOB/lastBuild/api/json)
RESULT=$(echo $JSON | grep -oe '"result":"\w\+"' | cut -d \" -f4 | tr -d '\n')

if [ -z $RESULT ]; then
    echo "Commit not allowed at the moment, a build is running" > /dev/stderr
    exit 1
elif [ $RESULT != "SUCCESS" ]; then
    # TODO Make a better regular expression in case Jenkins API changes
    # Capturing the culprit, last SVN user who committed
    CULPRIT=$(echo $JSON | grep -oe '/user/\w\+' | cut -d \/ -f3 | tail -1)
    # Capturing their full name too
    FULLNAME=$(echo $JSON | grep -oe '"fullName":".*"' | cut -d \" -f4)

    # Only the person who broke the build is allowed to fix it
    if [ $AUTHOR != $CULPRIT ]; then
        echo "Commit not allowed, the build is broken" > /dev/stderr
        echo "Contact SVN user $FULLNAME who broke the build" > /dev/stderr
        exit 1
    fi
fi
# Exit on all errors.
set -e